// =============================================
// 정부 지원금 데이터베이스
// =============================================
const BENEFITS_DB = [
  // ── 국가 지원금 ──────────────────────────────
  {
    id: 1,
    title: "기초생활수급자 생계급여",
    icon: "🍚",
    category: ["national", "family"],
    amount: "월 최대 713,102원 (1인 기준, 2025)",
    desc: "소득이 중위소득 30% 이하인 가구에 최저 생계 보장을 위한 급여를 지급합니다.",
    agency: "보건복지부",
    link: "https://www.bokjiro.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050076",
    conditions: {
      maxIncomeLevel: 3,
      householdTypes: ["single","couple","family","singleParent","elder","disabled"],
    },
    tags: ["생계급여", "기초수급", "저소득"],
    priority: 10,
  },
  {
    id: 2,
    title: "주거급여",
    icon: "🏠",
    category: ["national", "family"],
    amount: "월 최대 330,000원 (서울 1인 기준)",
    desc: "중위소득 48% 이하 가구에 임차료 또는 주택 수선비를 지원합니다.",
    agency: "국토교통부",
    link: "https://www.myhome.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050078",
    conditions: {
      maxIncomeLevel: 5,
      housing: ["rent", "monthly"],
    },
    tags: ["주거급여", "임차료", "저소득"],
    priority: 9,
  },
  {
    id: 3,
    title: "의료급여",
    icon: "🏥",
    category: ["national", "family"],
    amount: "의료비 본인부담 최소화",
    desc: "중위소득 40% 이하 가구에 외래·입원 의료비를 지원합니다.",
    agency: "보건복지부",
    link: "https://www.mohw.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050079",
    conditions: {
      maxIncomeLevel: 4,
    },
    tags: ["의료급여", "의료비", "기초수급"],
    priority: 9,
  },
  {
    id: 4,
    title: "청년 국민취업지원제도 (I유형)",
    icon: "💼",
    category: ["national", "youth"],
    amount: "월 50만원 × 최대 6개월 (구직촉진수당)",
    desc: "취업을 원하는 청년(15~69세)에게 취업지원서비스와 구직촉진수당을 지원합니다.",
    agency: "고용노동부",
    link: "https://www.kua.go.kr",
    applyLink: "https://www.kua.go.kr",
    conditions: {
      minAge: 15,
      maxAge: 34,
      employment: ["unemployed"],
      maxIncomeLevel: 6,
    },
    tags: ["청년", "취업", "구직", "수당"],
    priority: 8,
  },
  {
    id: 5,
    title: "청년도약계좌",
    icon: "💰",
    category: ["national", "youth"],
    amount: "월 최대 24,000원 기여금 + 이자",
    desc: "만 19~34세 청년의 자산 형성을 위해 정부가 기여금을 지원하는 적금 상품입니다.",
    agency: "금융위원회",
    link: "https://ylaccount.kinfa.or.kr",
    applyLink: "https://ylaccount.kinfa.or.kr",
    conditions: {
      minAge: 19,
      maxAge: 34,
      maxIncomeLevel: 7,
    },
    tags: ["청년", "저축", "자산형성"],
    priority: 7,
  },
  {
    id: 6,
    title: "청년 월세 특별지원",
    icon: "🏘️",
    category: ["national", "youth"],
    amount: "월 최대 20만원 × 12개월",
    desc: "독립 거주 청년의 주거비 부담 경감을 위해 월세를 지원합니다.",
    agency: "국토교통부",
    link: "https://youth.myhome.go.kr",
    applyLink: "https://youth.myhome.go.kr",
    conditions: {
      minAge: 19,
      maxAge: 34,
      housing: ["monthly"],
      householdTypes: ["single"],
      maxIncomeLevel: 6,
    },
    tags: ["청년", "월세", "주거"],
    priority: 8,
  },
  {
    id: 7,
    title: "아동수당",
    icon: "👶",
    category: ["national", "family"],
    amount: "월 100,000원",
    desc: "만 8세 미만 아동에게 매월 10만원을 지급합니다.",
    agency: "보건복지부",
    link: "https://www.bokjiro.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050082",
    conditions: {
      minChildCount: 1,
    },
    tags: ["아동", "육아", "수당"],
    priority: 8,
  },
  {
    id: 8,
    title: "부모급여 (영아수당)",
    icon: "🍼",
    category: ["national", "family"],
    amount: "0세 월 100만원 / 1세 월 50만원",
    desc: "0~1세 자녀를 가정에서 양육하는 부모에게 매월 지급합니다.",
    agency: "보건복지부",
    link: "https://www.bokjiro.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050083",
    conditions: {
      minChildCount: 1,
      extras: ["newborn"],
    },
    tags: ["영아", "육아", "부모급여"],
    priority: 9,
  },
  {
    id: 9,
    title: "첫만남이용권",
    icon: "🎁",
    category: ["national", "family"],
    amount: "200만원 (첫째) / 300만원 (둘째 이상)",
    desc: "출생아 가정에 바우처를 지급하여 초기 양육 비용을 지원합니다.",
    agency: "보건복지부",
    link: "https://www.bokjiro.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050084",
    conditions: {
      minChildCount: 1,
      extras: ["newborn"],
    },
    tags: ["출산", "바우처", "신생아"],
    priority: 9,
  },
  {
    id: 10,
    title: "기초연금",
    icon: "👴",
    category: ["national", "senior"],
    amount: "월 최대 334,810원 (2025)",
    desc: "만 65세 이상 소득 하위 70%에 해당하는 어르신에게 매월 지급합니다.",
    agency: "보건복지부",
    link: "https://www.bokjiro.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050085",
    conditions: {
      minAge: 65,
      maxIncomeLevel: 7,
    },
    tags: ["노인", "연금", "어르신"],
    priority: 9,
  },
  {
    id: 11,
    title: "장애인연금",
    icon: "♿",
    category: ["national", "disabled"],
    amount: "월 최대 342,510원",
    desc: "중증장애인 중 소득인정액이 일정 기준 이하인 분께 지급합니다.",
    agency: "보건복지부",
    link: "https://www.bokjiro.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050086",
    conditions: {
      maxIncomeLevel: 7,
      extras: ["disability"],
    },
    tags: ["장애인", "연금"],
    priority: 9,
  },
  {
    id: 12,
    title: "한부모가족 양육비 지원",
    icon: "👩‍👧",
    category: ["national", "family"],
    amount: "자녀 1인당 월 최대 200,000원",
    desc: "한부모 및 조손가족의 자녀 양육을 위한 양육비를 지원합니다.",
    agency: "여성가족부",
    link: "https://www.mogef.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050087",
    conditions: {
      householdTypes: ["singleParent"],
      maxIncomeLevel: 6,
      minChildCount: 1,
    },
    tags: ["한부모", "양육비", "아동"],
    priority: 9,
  },
  {
    id: 13,
    title: "실업급여 (구직급여)",
    icon: "📋",
    category: ["national", "youth"],
    amount: "퇴직 전 평균임금의 60% × 최대 9개월",
    desc: "비자발적 실직자에게 구직활동을 하는 동안 생계비를 지원합니다.",
    agency: "고용노동부",
    link: "https://www.ei.go.kr",
    applyLink: "https://www.ei.go.kr",
    conditions: {
      employment: ["unemployed"],
    },
    tags: ["실업", "구직", "급여"],
    priority: 8,
  },
  {
    id: 14,
    title: "국가보훈대상자 생활조정수당",
    icon: "🎖️",
    category: ["national"],
    amount: "월 최대 500,000원",
    desc: "생활이 어려운 국가유공자 및 그 유족에게 생활지원금을 지급합니다.",
    agency: "국가보훈부",
    link: "https://www.mpva.go.kr",
    applyLink: "https://www.mpva.go.kr",
    conditions: {
      extras: ["veteran"],
      maxIncomeLevel: 5,
    },
    tags: ["보훈", "국가유공자"],
    priority: 8,
  },
  {
    id: 15,
    title: "임산부 국민행복카드",
    icon: "🤰",
    category: ["national", "family"],
    amount: "100만원 (단태아) / 140만원 (다태아)",
    desc: "임신·출산 관련 의료비 및 물품 구입에 사용할 수 있는 바우처를 지급합니다.",
    agency: "보건복지부",
    link: "https://www.bokjiro.go.kr",
    applyLink: "https://www.gov.kr/portal/service/serviceInfo/PTR000050088",
    conditions: {
      extras: ["pregnant"],
    },
    tags: ["임산부", "출산", "바우처"],
    priority: 9,
  },
  // ── 서울 지자체 ──────────────────────────────
  {
    id: 101,
    title: "서울 청년수당",
    icon: "🌆",
    category: ["local", "youth"],
    amount: "월 50만원 × 최대 6개월",
    desc: "서울시 거주 미취업 청년에게 활동비와 취업지원서비스를 제공합니다.",
    agency: "서울특별시",
    link: "https://youth.seoul.go.kr",
    applyLink: "https://youth.seoul.go.kr",
    conditions: {
      minAge: 19,
      maxAge: 34,
      region: ["seoul"],
      employment: ["unemployed", "student"],
      maxIncomeLevel: 6,
    },
    tags: ["청년", "서울", "지자체"],
    priority: 7,
  },
  {
    id: 102,
    title: "서울 임산부 교통비 지원",
    icon: "🚌",
    category: ["local", "family"],
    amount: "70만원 (교통카드 포인트)",
    desc: "서울시 거주 임산부에게 대중교통 이용 교통비를 지원합니다.",
    agency: "서울특별시",
    link: "https://news.seoul.go.kr",
    applyLink: "https://news.seoul.go.kr",
    conditions: {
      region: ["seoul"],
      extras: ["pregnant"],
    },
    tags: ["임산부", "서울", "교통비"],
    priority: 7,
  },
  {
    id: 103,
    title: "서울형 기초보장",
    icon: "🏙️",
    category: ["local"],
    amount: "월 최대 40만원 추가 지원",
    desc: "국가 기초수급 탈락 가구에 서울시가 별도로 생계비를 지원합니다.",
    agency: "서울특별시",
    link: "https://welfare.seoul.go.kr",
    applyLink: "https://welfare.seoul.go.kr",
    conditions: {
      region: ["seoul"],
      maxIncomeLevel: 4,
    },
    tags: ["서울", "생계", "지자체"],
    priority: 7,
  },
  // ── 경기도 ──────────────────────────────────
  {
    id: 201,
    title: "경기도 청년 복지포인트",
    icon: "🏞️",
    category: ["local", "youth"],
    amount: "연 120만원 (복지포인트)",
    desc: "경기도 내 중소기업 재직 청년에게 복지포인트를 지원합니다.",
    agency: "경기도",
    link: "https://www.gg.go.kr",
    applyLink: "https://www.gg.go.kr",
    conditions: {
      minAge: 18,
      maxAge: 34,
      region: ["gyeonggi"],
      employment: ["employed", "partTime"],
    },
    tags: ["청년", "경기도", "복지포인트"],
    priority: 6,
  },
  {
    id: 202,
    title: "경기도 산후조리 지원",
    icon: "🍀",
    category: ["local", "family"],
    amount: "최대 100만원",
    desc: "경기도 거주 출산 가정에 산후조리 비용을 지원합니다.",
    agency: "경기도",
    link: "https://www.gg.go.kr",
    applyLink: "https://www.gg.go.kr",
    conditions: {
      region: ["gyeonggi"],
      extras: ["newborn"],
    },
    tags: ["출산", "경기도", "산후조리"],
    priority: 6,
  },
  // ── 부산 ─────────────────────────────────────
  {
    id: 301,
    title: "부산 청년 취업 장려금",
    icon: "🌊",
    category: ["local", "youth"],
    amount: "200만원 (1회성)",
    desc: "부산 소재 기업에 취업하는 청년에게 장려금을 지원합니다.",
    agency: "부산광역시",
    link: "https://www.busan.go.kr",
    applyLink: "https://www.busan.go.kr",
    conditions: {
      minAge: 18,
      maxAge: 34,
      region: ["busan"],
      employment: ["employed"],
    },
    tags: ["청년", "부산", "취업"],
    priority: 6,
  },
  // ── 노인/어르신 ──────────────────────────────
  {
    id: 401,
    title: "노인 장기요양보험 급여",
    icon: "🧓",
    category: ["national", "senior"],
    amount: "요양등급별 한도액 내 90% 지원",
    desc: "일상생활 수행이 어려운 65세 이상 노인에게 방문요양, 시설요양 등을 제공합니다.",
    agency: "국민건강보험공단",
    link: "https://www.nhis.or.kr",
    applyLink: "https://www.nhis.or.kr",
    conditions: {
      minAge: 65,
      extras: ["longTermCare"],
    },
    tags: ["노인", "요양", "돌봄"],
    priority: 8,
  },
  {
    id: 402,
    title: "노인 일자리 및 사회활동 지원",
    icon: "👷",
    category: ["national", "senior"],
    amount: "월 최대 297,000원",
    desc: "65세 이상 노인에게 사회참여 및 소득 보충을 위한 일자리를 제공합니다.",
    agency: "보건복지부",
    link: "https://www.kordi.or.kr",
    applyLink: "https://www.bokjiro.go.kr",
    conditions: {
      minAge: 65,
    },
    tags: ["노인", "일자리", "사회활동"],
    priority: 7,
  },
  // ── 다문화 ─────────────────────────────────
  {
    id: 501,
    title: "다문화가족 지원 서비스",
    icon: "🌏",
    category: ["national", "family"],
    amount: "한국어교육, 통번역, 생활지원 서비스",
    desc: "다문화가족에게 한국어 교육, 취업 지원, 자녀 언어발달 지원 등을 제공합니다.",
    agency: "여성가족부",
    link: "https://liveinkorea.kr",
    applyLink: "https://liveinkorea.kr",
    conditions: {
      extras: ["multicultural"],
    },
    tags: ["다문화", "외국인"],
    priority: 7,
  },
  // ── 교육 ────────────────────────────────────
  {
    id: 601,
    title: "국가장학금 (한국장학재단)",
    icon: "🎓",
    category: ["national", "youth"],
    amount: "연 최대 700만원",
    desc: "소득 8분위 이하 대학(원)생에게 등록금을 지원합니다.",
    agency: "한국장학재단",
    link: "https://www.kosaf.go.kr",
    applyLink: "https://www.kosaf.go.kr",
    conditions: {
      minAge: 18,
      maxAge: 34,
      employment: ["student"],
      maxIncomeLevel: 8,
    },
    tags: ["장학금", "교육", "대학"],
    priority: 8,
  },
  // ── 에너지 ───────────────────────────────────
  {
    id: 701,
    title: "에너지바우처 (전기·가스비 지원)",
    icon: "⚡",
    category: ["national"],
    amount: "여름 최대 33,800원 / 겨울 최대 195,000원",
    desc: "소득이 낮고 에너지 취약계층 가구에 전기·가스·등유 구입 비용을 지원합니다.",
    agency: "산업통상자원부",
    link: "https://www.energyv.or.kr",
    applyLink: "https://www.energyv.or.kr",
    conditions: {
      maxIncomeLevel: 4,
      householdTypes: ["elder", "disabled", "singleParent", "single"],
    },
    tags: ["에너지", "전기", "가스", "바우처"],
    priority: 7,
  },
];

// 지역별 구 데이터
const DISTRICTS = {
  seoul: ["강남구","강동구","강북구","강서구","관악구","광진구","구로구","금천구","노원구","도봉구","동대문구","동작구","마포구","서대문구","서초구","성동구","성북구","송파구","양천구","영등포구","용산구","은평구","종로구","중구","중랑구"],
  busan: ["강서구","금정구","기장군","남구","동구","동래구","부산진구","북구","사상구","사하구","서구","수영구","연제구","영도구","중구","해운대구"],
  gyeonggi: ["수원시","성남시","의정부시","안양시","부천시","광명시","평택시","동두천시","안산시","고양시","과천시","구리시","남양주시","오산시","시흥시","군포시","의왕시","하남시","용인시","파주시","이천시","안성시","김포시","화성시","광주시","양주시","포천시","여주시"],
  incheon: ["강화군","계양구","남동구","동구","미추홀구","부평구","서구","연수구","옹진군","중구"],
  daegu: ["남구","달서구","달성군","동구","북구","서구","수성구","중구"],
  gwangju: ["광산구","남구","동구","북구","서구"],
  daejeon: ["대덕구","동구","서구","유성구","중구"],
  ulsan: ["남구","동구","북구","울주군","중구"],
  gangwon: ["춘천시","원주시","강릉시","동해시","태백시","속초시","삼척시"],
  chungbuk: ["청주시","충주시","제천시","보은군","옥천군","영동군","증평군","진천군","괴산군","음성군","단양군"],
  chungnam: ["천안시","공주시","보령시","아산시","서산시","논산시","계룡시","당진시"],
  jeonbuk: ["전주시","군산시","익산시","정읍시","남원시","김제시"],
  jeonnam: ["목포시","여수시","순천시","나주시","광양시"],
  gyeongbuk: ["포항시","경주시","김천시","안동시","구미시","영주시","영천시","상주시","문경시","경산시"],
  gyeongnam: ["창원시","진주시","통영시","사천시","김해시","밀양시","거제시","양산시"],
  jeju: ["제주시","서귀포시"],
  sejong: ["세종시"],
};

// 중위소득 기준 데이터
const INCOME_DATA = [
  { level: 1, label: "기초수급 이하", amount: "월 약 80만원 이하 (1인)", medianPct: 30 },
  { level: 2, label: "중위소득 30~40%", amount: "월 약 80~107만원 (1인)", medianPct: 40 },
  { level: 3, label: "중위소득 40~50%", amount: "월 약 107~134만원 (1인)", medianPct: 50 },
  { level: 4, label: "중위소득 50~60%", amount: "월 약 134~160만원 (1인)", medianPct: 60 },
  { level: 5, label: "중위소득 60~70%", amount: "월 약 160~187만원 (1인)", medianPct: 70 },
  { level: 6, label: "중위소득 70~80%", amount: "월 약 187~213만원 (1인)", medianPct: 80 },
  { level: 7, label: "중위소득 80~100%", amount: "월 약 213~239만원 (1인)", medianPct: 100 },
  { level: 8, label: "중위소득 100~120%", amount: "월 약 239~286만원 (1인)", medianPct: 120 },
  { level: 9, label: "중위소득 120~150%", amount: "월 약 286~358만원 (1인)", medianPct: 150 },
  { level: 10, label: "고소득 (150% 초과)", amount: "월 약 358만원 이상 (1인)", medianPct: 999 },
];
